config/routes.rb
Rails.application.routes.draw do
  resources :projects

  devise_for :users, :skip => [:registrations],
                     :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:edit, :update]

  resource :github_webhooks, only: :create, defaults: { formats: :json }

  root to: "projects#index"
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :pull_requests

  before_validation :ensure_github_webhook_secret
  before_validation :downcase_repo

  validates_format_of :repo, with: /\A[^\/]+\/[^\/]+\Z/
  validates_presence_of :repo, :tracker_project_id
  validates_uniqueness_of :repo

  private

  def ensure_github_webhook_secret
    self.github_webhook_secret ||= (0...40).map { (33 + rand(93)).chr }.join
  end

  def downcase_repo
    self.repo = repo.downcase
  end
end

app/models/pull_request.rb
class PullRequest < ActiveRecord::Base
  belongs_to :project

  validates_uniqueness_of :number, scope: :project_id

  def url
    "https://github.com/#{project.repo}/pull/#{number}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:github]

  has_many :projects

  def self.find_for_github_oauth(auth)
    user = where(email: auth.info.email).first
    user ||= where(auth.slice(:provider, :uid)).first
    user ||= User.new
    store_github_info(user, auth)
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.github_data"] && session["devise.github_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  private

    def self.store_github_info(user, auth)
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
      user.email = auth.info.email
      user.github_nickname = auth.info.nickname
      user.name = auth.info.name
      user.gravatar_url = auth.info.image
      user.github_token = auth.credentials.token
      user.save!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_action :authenticate_user!
end

app/controllers/github_webhooks_controller.rb
class GithubWebhooksController < ActionController::Base
  include GithubWebhook::Processor

  def github_pull_request(payload)
    case payload[:action]
    when "opened"
      PullRequestCreator.new(payload, @project).run
    when "closed"
      PullRequestCloser.new(payload, @project).run
    when "synchronize"
      PullRequestUpdater.new(payload, @project).run
    when "reopened"
      PullRequestReopener.new(payload, @project).run
    end
  end

  def webhook_secret(payload)
    repo = pull_request_payload_repo(payload)
    @project = Project.find_by_repo(repo)
    raise ActiveRecord::RecordNotFound.new("No project named #{repo} found") unless @project
    @project.github_webhook_secret
  end

  private

  def pull_request_payload_repo(payload)
    (params[:zen] ? payload[:repository][:full_name] : payload[:pull_request][:base][:repo][:full_name]).downcase
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :ensure_current_user_pivotal_tracker_api_token, only: :index
  before_action :set_project, only: :destroy
  before_action :set_tracker_projects, only: [:index, :new, :create]

  def index
    @projects = current_user.projects
  end

  def new
    @project = current_user.projects.build
  end

  def create
    @project = ProjectCreator.new(project_params).run(current_user)
    if @project.persisted?
      redirect_to projects_path
    else
      render :new
    end
  end

  def destroy
    GithubUnsubscriber.new(@project).run(current_user)
    @project.destroy
    redirect_to projects_path
  end

  private

  def set_project
    @project = current_user.projects.find(params[:id])
  end

  def set_tracker_projects
    return unless current_user.pivotal_tracker_api_token
    account = Tracker::Account.new(current_user.pivotal_tracker_api_token)
    @tracker_projects = account.projects.map { |p| [ p.name, p.id ] }
  end

  def project_params
    params.require(:project).permit(:repo, :tracker_project_id)
  end

  def ensure_current_user_pivotal_tracker_api_token
    if current_user.pivotal_tracker_api_token.blank?
      redirect_to edit_user_path(current_user), alert: "Please set up your Pivotal Tracker API token first."
      false
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.find_for_github_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      # session["devise.github_data"] = request.env["omniauth.auth"]
      flash[:error] = "Please ask a Wagon administrator to remove your account first"
      redirect_to unauthenticated_root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to projects_path, notice: "Pivotal Tracker API token has been saved"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:pivotal_tracker_api_token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def repo_url(repo)
    link_to repo, "https://github.com/#{repo}", target: :blank
  end

  def pivotal_tracker_project_url(id, tracker_projects)
    name = tracker_projects.select { |pair| pair.last == id.to_i }.first.try(:first)
    link_to name, "https://www.pivotaltracker.com/s/projects/#{id}", target: :blank
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mergehook</title>
  <link href='http://fonts.googleapis.com/css?family=Inder' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
    <%= link_to(current_user.github_nickname, edit_user_path(current_user)) %>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  <% end %>

  <p><%= flash[:alert] %></p>
  <p><%= flash[:notice] %></p>

  <%= yield %>

  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% f.object.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>

  <%= f.label :repo %>
  <%= f.text_field :repo, placeholder: "owner/repo_name" %>

  <br>

  <%= f.label :tracker_project_id %>

  <%= f.select :tracker_project_id, @tracker_projects %>

  <br>
  <%= f.submit %>
<% end %>

app/views/projects/index.html.erb
<% if @projects.any? %>
  <table>
    <thead>
      <tr>
        <th>GitHub</th>
        <th>Pivotal Tracker</th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
      <tr>
        <td><%= repo_url project.repo %></td>
        <td><%= pivotal_tracker_project_url(project.tracker_project_id, @tracker_projects) %></td>
        <td>
          <%= link_to "Delete", project_path(project), method: :delete, confirm: "Are you sure?" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<%= render 'form' %>

<%= link_to "Back to projects", projects_path %>

app/views/users/edit.html.erb
<%= form_for current_user do |f| %>
  <% f.object.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>

  <%= f.label :pivotal_tracker_api_token %>

  <%= f.text_field :pivotal_tracker_api_token %>

  <br>

  You can go to your <a href="https://www.pivotaltracker.com/profile" target="_blank">Pivotal Tracker Profile</a>
  page and scroll right to the bottom. You'll find the token to copy paste.

  <br>

  <%= f.submit %>
<% end %>